name: Deploy CloudFormation

on:
  push:
    branches:
      - deploy  # deploブランチへのプッシュでデプロイがトリガーされる

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHubリポジトリからコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # AWS CLIの設定
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # 使用するリージョンを指定

      # CloudFormationスタックのデプロイまたは更新
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name my-serverless-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-west-2
